  on: "workflow_dispatch"
  jobs:
    build_container:
      name: Build Container
      runs-on: ubuntu-latest
      permissions:
        contents: read
        packages: write
      steps:
        # Standard checkout step
        - name: Checkout code
          id: git_checkout
          uses: actions/checkout@v3
        # Use qemu to perform multiplatform builds
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v3
        # Use docker buildx to build multi-platform containers
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
          with:
            use: true
            install: true
            config-inline: |
              [worker.oci]
                max-parallelism = 2
        # Log in to GitHub Container registry
        - name: Login to GitHub Container Registry
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
        # Build and push docker images
        - name: Build and Push Docker Image
          uses: docker/build-push-action@v5
          with:
            context: ./.github/assets/cowsay
            platforms: linux/amd64,linux/arm64
            push: true
            tags: ghcr.io/${{ github.repository_owner }}/cowsay:3.0.3,ghcr.io/${{ github.repository_owner }}/cowsay:latest
